#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""高色アトラスを既存45 actor / 9地形slotのGRB16へコンパイルする。"""

from __future__ import annotations

import argparse
from pathlib import Path

from mkhighcolor import grb16, read_png, rgb_from_grb16

HERO_BOXES = (
    (60, 140, 285, 480), (315, 150, 535, 480), (565, 145, 780, 480),
    (805, 155, 1040, 480), (1060, 145, 1290, 480), (1290, 70, 1535, 430),
    (20, 550, 245, 850), (260, 590, 485, 890), (515, 580, 755, 920),
    (765, 585, 980, 920), (1060, 585, 1280, 920), (1250, 800, 1535, 920),
)
OBJECT_BOXES = (
    (65, 60, 220, 245), (300, 60, 450, 245), (515, 70, 685, 245),
    (715, 65, 1000, 245), (1055, 60, 1210, 245), (1245, 65, 1505, 245),
    (50, 325, 225, 510), (245, 325, 510, 510), (530, 260, 795, 530),
    (850, 330, 1020, 510), (1075, 320, 1235, 510), (1290, 320, 1480, 510),
    (45, 580, 240, 680), (325, 535, 420, 720), (535, 555, 710, 715),
    (805, 540, 1010, 725), (1080, 565, 1220, 710), (1285, 540, 1470, 730),
    (40, 755, 235, 945), (285, 750, 480, 950), (535, 735, 725, 950),
    (850, 740, 920, 950), (1030, 730, 1235, 960), (1280, 735, 1455, 950),
)


def is_key(rgb: tuple[int, int, int]) -> bool:
    red, green, blue = rgb
    return red > 180 and blue > 180 and green < 100


def sample_sprite(image, box, out_width: int, out_height: int) -> list[list[int]]:
    width, height, pixels = image
    left, top, right, bottom = box
    valid_box = 0 <= left < right <= width and 0 <= top < bottom <= height
    if not valid_box:
        raise ValueError("Sprite crop is outside the source atlas")
    opaque = [(x, y) for y in range(top, bottom) for x in range(left, right)
              if not is_key(pixels[y * width + x])]
    has_opaque = bool(opaque)
    if not has_opaque:
        raise ValueError("Sprite crop contains only the transparency key")
    left, right = min(x for x, _ in opaque), max(x for x, _ in opaque) + 1
    top, bottom = min(y for _, y in opaque), max(y for _, y in opaque) + 1
    result = []
    for y in range(out_height):
        source_y = top + (2 * y + 1) * (bottom - top) // (2 * out_height)
        row = []
        for x in range(out_width):
            source_x = left + (2 * x + 1) * (right - left) // (2 * out_width)
            rgb = pixels[source_y * width + source_x]
            transparent = is_key(rgb)
            # 透明性は原画のkeyから決める。黒も不透明画素なのでword0を予約する。
            row.append(0 if transparent else max(1, grb16(rgb)))
        result.append(row)
    return result


def canvas(sprite, left=0, top=0) -> list[int]:
    result = [0] * 256
    for y, row in enumerate(sprite):
        for x, word in enumerate(row):
            result[(top + y) * 16 + left + x] = word
    return result


def foreground_assets(hero_path: Path, objects_path: Path):
    hero, objects = read_png(hero_path), read_png(objects_path)
    expected_size = hero[:2] == (1536, 1024) and objects[:2] == (1536, 1024)
    if not expected_size:
        raise ValueError("Expected the reviewed 1536x1024 source atlases")
    actors = []
    for box in HERO_BOXES[:11]:
        sprite = sample_sprite(hero, box, 16, 32)
        actors.extend((canvas(sprite[:16]), canvas(sprite[16:])))
    dead = sample_sprite(hero, HERO_BOXES[11], 32, 16)
    actors.extend((canvas([row[:16] for row in dead]), canvas([row[16:] for row in dead])))
    def obj(i, w=16, h=16):
        return sample_sprite(objects, OBJECT_BOXES[i], w, h)
    actors.extend(canvas(obj(i)) for i in range(6))
    actors.extend(canvas(obj(i, 8, 8)) for i in (12, 13, 9, 10, 11))
    boss = obj(8, 32, 32)
    for top, left in ((0, 0), (0, 16), (16, 0), (16, 16)):
        actors.append(canvas([row[left:left + 16] for row in boss[top:top + 16]]))
    actors.extend(canvas(obj(i, 8, 8)) for i in (14, 15))
    actors.extend(canvas(obj(i)) for i in (6, 7))
    actors.extend(canvas(obj(i, 8, 8)) for i in (11, 16))
    ground = canvas(obj(17, 16, 8), 0, 8)
    pole = canvas(obj(21, 2, 16), 14, 0)
    flag_base = ground.copy()
    flag_base[:128] = pole[:128]
    terrain = [[0] * 256, ground, canvas(obj(18)), canvas(obj(19)),
               canvas(obj(16, 8, 8), 8, 0), canvas(obj(20)),
               pole, flag_base, canvas(obj(23, 16, 8), 0, 8)]
    assert len(actors) == 45 and len(terrain) == 9
    return actors, terrain


def write_c(path: Path, actors, terrain) -> None:
    lines = ["// Generated by x68k/tools/mkforeground.py; do not edit.",
             "#include <stdint.h>", "// Row-major GRB16; zero = transparent, opaque black = 1."]
    for name, patterns in (("actor", actors), ("background", terrain)):
        lines.append(f"const uint16_t g_highcolor_{name}_patterns[{len(patterns)}][256] = {{")
        for pattern in patterns:
            lines.append("    {")
            for y in range(16):
                lines.append("        {0},".format(",".join(f"0x{c:04X}" for c in pattern[y * 16:y * 16 + 16])))
            lines.append("    },")
        lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_preview(path: Path, actors, terrain) -> None:
    patterns = actors + terrain
    width, height = 16 * 9, 16 * 6
    pixels = bytearray()
    for y in range(height):
        for x in range(width):
            index = (y // 16) * 9 + x // 16
            word = patterns[index][(y % 16) * 16 + x % 16]
            rgb = rgb_from_grb16(word) if word else (20, 24, 40)
            pixels.extend(rgb)
    path.write_bytes(f"P6\n{width} {height}\n255\n".encode() + pixels)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("assets", type=Path)
    parser.add_argument("out", type=Path)
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()
    actors, terrain = foreground_assets(args.assets / "hero-highcolor-keyed.png",
                                       args.assets / "objects-highcolor-atlas.png")
    write_c(args.out, actors, terrain)
    wants_preview = args.preview is not None
    if wants_preview:
        write_preview(args.preview, actors, terrain)
    print(f"High-color foreground: {len(actors)} actor + {len(terrain)} terrain patterns, "
          f"{len({word for pattern in actors + terrain for word in pattern if word})} colors")


if __name__ == "__main__":
    main()
