#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""4:3の2x2 PNGアトラスを4面の320x240・直接色背景へ変換する。"""

from __future__ import annotations

import argparse
from pathlib import Path

from mkhighcolor import grb16, read_png

WIDTH, HEIGHT, STAGES = 320, 240, 4


def backgrounds_from_atlas(width: int, height: int,
                           pixels: list[tuple[int, int, int]]) -> list[list[list[int]]]:
    valid_dimensions = (width > 0 and height > 0 and width % 2 == 0 and height % 2 == 0
                        and width * 3 == height * 4)
    if not valid_dimensions:
        raise ValueError("Expected an even-sized 4:3 atlas with four equal quadrants")
    valid_count = len(pixels) == width * height
    if not valid_count:
        raise ValueError("Atlas pixel count does not match its dimensions")

    source_width, source_height = width // 2, height // 2
    columns = [(2 * x + 1) * source_width // (2 * WIDTH) for x in range(WIDTH)]
    rows = [(2 * y + 1) * source_height // (2 * HEIGHT) for y in range(HEIGHT)]
    backgrounds = []
    for stage in range(STAGES):
        left = (stage % 2) * source_width
        top = (stage // 2) * source_height
        background = []
        for y in rows:
            offset = (top + y) * width + left
            row = []
            for x in columns:
                word = grb16(pixels[offset + x])
                is_transparent = word == 0
                # 全wordへのOR 1は緑の第6bitまで変えるため、透過wordだけを置換する。
                row.append(1 if is_transparent else word)
            background.append(row)
        backgrounds.append(background)
    return backgrounds


def stage_backgrounds(atlas: Path) -> list[list[list[int]]]:
    return backgrounds_from_atlas(*read_png(atlas))


def write_c(path: Path, backgrounds: list[list[list[int]]]) -> None:
    lines = ["// Generated by x68k/tools/mkstagehighcolor.py; do not edit.",
             "#include <stdint.h>",
             "const uint16_t g_x68k_stage_backgrounds[4][240][320] = {"]
    for background in backgrounds:
        lines.append("    {")
        for row in background:
            lines.append("        {" + ",".join(f"0x{word:04X}" for word in row) + "},")
        lines.append("    },")
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("atlas", type=Path)
    parser.add_argument("out", type=Path)
    args = parser.parse_args()
    backgrounds = stage_backgrounds(args.atlas)
    write_c(args.out, backgrounds)
    for stage, background in enumerate(backgrounds, start=1):
        colors = len({word for row in background for word in row})
        print(f"Stage 1-{stage}: 320x240, {colors} opaque GRB16 colors")


if __name__ == "__main__":
    main()
